package cn.gtmap.onemap.server.thirdparty.kanq.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2013-12-27T11:07:04.884+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://service.ser.kanq.com", name = "userPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserPortType {

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUser", output = "urn:getUserResponse")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUser")
    @WebMethod(action = "urn:getUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserResponse")
    public java.lang.String getUser(
        @WebParam(name = "businessType", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String businessType
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUserStr", output = "urn:getUserStrResponse")
    @RequestWrapper(localName = "getUserStr", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserStr")
    @WebMethod(action = "urn:getUserStr")
    @ResponseWrapper(localName = "getUserStrResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserStrResponse")
    public java.lang.String getUserStr(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "businessType", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String businessType
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUserStr2", output = "urn:getUserStr2Response")
    @RequestWrapper(localName = "getUserStr2", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserStr2")
    @WebMethod(action = "urn:getUserStr2")
    @ResponseWrapper(localName = "getUserStr2Response", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserStr2Response")
    public java.lang.String getUserStr2(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "type", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String type
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:QueryUserRights", output = "urn:QueryUserRightsResponse")
    @RequestWrapper(localName = "QueryUserRights", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.QueryUserRights")
    @WebMethod(operationName = "QueryUserRights", action = "urn:QueryUserRights")
    @ResponseWrapper(localName = "QueryUserRightsResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.QueryUserRightsResponse")
    public java.lang.String queryUserRights(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "type", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String type
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUserByName", output = "urn:getUserByNameResponse")
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserByName")
    @WebMethod(action = "urn:getUserByName")
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserByNameResponse")
    public java.lang.String getUserByName(
        @WebParam(name = "userName", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String userName
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUserByCode2", output = "urn:getUserByCode2Response")
    @RequestWrapper(localName = "getUserByCode2", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserByCode2")
    @WebMethod(action = "urn:getUserByCode2")
    @ResponseWrapper(localName = "getUserByCode2Response", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserByCode2Response")
    public java.lang.String getUserByCode2(
        @WebParam(name = "userCode", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String userCode
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:QueryRolesByLicense", output = "urn:QueryRolesByLicenseResponse")
    @RequestWrapper(localName = "QueryRolesByLicense", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.QueryRolesByLicense")
    @WebMethod(operationName = "QueryRolesByLicense", action = "urn:QueryRolesByLicense")
    @ResponseWrapper(localName = "QueryRolesByLicenseResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.QueryRolesByLicenseResponse")
    public java.lang.String queryRolesByLicense(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "type", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String type
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getOrganByUser", output = "urn:getOrganByUserResponse")
    @RequestWrapper(localName = "getOrganByUser", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetOrganByUser")
    @WebMethod(action = "urn:getOrganByUser")
    @ResponseWrapper(localName = "getOrganByUserResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetOrganByUserResponse")
    public java.lang.String getOrganByUser(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "userid", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String userid
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUserByCode", output = "urn:getUserByCodeResponse")
    @RequestWrapper(localName = "getUserByCode", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserByCode")
    @WebMethod(action = "urn:getUserByCode")
    @ResponseWrapper(localName = "getUserByCodeResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUserByCodeResponse")
    public java.lang.String getUserByCode(
        @WebParam(name = "userCode", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String userCode
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getRoleByUser", output = "urn:getRoleByUserResponse")
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetRoleByUser")
    @WebMethod(action = "urn:getRoleByUser")
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetRoleByUserResponse")
    public java.lang.String getRoleByUser(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "userid", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String userid
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:modifyPwd", output = "urn:modifyPwdResponse")
    @RequestWrapper(localName = "modifyPwd", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.ModifyPwd")
    @WebMethod(action = "urn:modifyPwd")
    @ResponseWrapper(localName = "modifyPwdResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.ModifyPwdResponse")
    public java.lang.String modifyPwd(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "userName", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String userName,
        @WebParam(name = "newPwd", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String newPwd
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:login", output = "urn:loginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.Login")
    @WebMethod(action = "urn:login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "user", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String user,
        @WebParam(name = "pwd", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String pwd
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getUser2", output = "urn:getUser2Response")
    @RequestWrapper(localName = "getUser2", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUser2")
    @WebMethod(action = "urn:getUser2")
    @ResponseWrapper(localName = "getUser2Response", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetUser2Response")
    public java.lang.String getUser2(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "type", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String type
    );

    @WebResult(name = "return", targetNamespace = "http://service.ser.kanq.com")
    @Action(input = "urn:getRoleStr", output = "urn:getRoleStrResponse")
    @RequestWrapper(localName = "getRoleStr", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetRoleStr")
    @WebMethod(action = "urn:getRoleStr")
    @ResponseWrapper(localName = "getRoleStrResponse", targetNamespace = "http://service.ser.kanq.com", className = "cn.gtmap.onemap.server.thirdparty.kanq.user.GetRoleStrResponse")
    public java.lang.String getRoleStr(
        @WebParam(name = "license", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String license,
        @WebParam(name = "businessType", targetNamespace = "http://service.ser.kanq.com")
        java.lang.String businessType
    );
}
