{
	"coordinateVisible":true,
	"createAt":"2019-04-17 16:06:52",
	"defaultRegionCode":"320000",
	"description":"test",
	"dockWidgets":[
		{
			"collapsible":false,
			"config":{
				"expandLevel":1,
				"groupByYear":false
			},
			"display":true,
			"icon":"glyphicon glyphicon-tasks",
			"id":"DataList",
			"label":"数据",
			"open":false,
			"url":"DataList",
			"weight":0
		},
		{
			"collapsible":false,
			"config":{
				"autoCreateProject":false,
				"exportXls":false,
				"identifyLayers":[],
				"modifyProVideo":false,
				"newProjectLayer":[],
				"panoramaSwitch":"off",
				"popupStyle":"layer",
				"proType":[
					{
						"color":"#ffb61e",
						"name":"建设用地"
					},
					{
						"color":"#00bc12",
						"name":"农用地"
					},
					{
						"color":"#ff2d51",
						"name":"未利用地"
					},
					{
						"color":"#000000",
						"name":"其他"
					}
				],
				"searchVideoByXy":false,
				"showArcCenter":false,
				"showStatus":false,
				"showVideoByCluster":false,
				"style":"list",
				"supervise":false,
				"txVersionEnable":false,
				"txtSymbol":{
					"color":"#32bfef",
					"fontSize":"12"
				}
			},
			"display":true,
			"icon":"glyphicon glyphicon-facetime-video",
			"id":"VideoManager",
			"label":"视频",
			"open":false,
			"url":"VideoManager",
			"weight":0
		}
	],
	"geometryService":{
		"url":"http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer"
	},
	"logo":"/omp/static/img/new/logo.jpg",
	"map":{
		"baseLayers":[],
		"defaultScale":0,
		"initExtent":{
			"spatialReference":{
				"latestWkid":4490,
				"wkid":4490
			},
			"xmax":119.20281593600895,
			"xmin":118.97069161931269,
			"ymax":32.11145708552732,
			"ymin":31.96169946185231
		},
		"operationalLayers":[
			{
				"alias":"供地地块",
				"alpha":1,
				"category":"业务图层",
				"group":"0165f5b9785ee4e4e48965f5a70b0027",
				"id":"016a061eb88f4028daf06a05eccb0039",
				"index":1,
				"name":"GDDK_320000",
				"type":"dynamic",
				"url":"http://192.168.90.112:6070/oms/arcgisrest/业务图层/GDDK_320000/MapServer",
				"visible":true,
				"xMaxExtent":121.93722808700011,
				"xMinExtent":116.38282509600003,
				"xzdm":"320000",
				"yMaxExtent":35.12104033800006,
				"yMinExtent":30.764454922000027,
				"year":2016
			},
			{
				"alias":"报批地块",
				"alpha":1,
				"category":"业务图层",
				"group":"0165f5b9785ee4e4e48965f5a70b0027",
				"id":"016a05eebf1b4028daf06a05eccb0017",
				"index":2,
				"name":"BPDK_320000",
				"type":"dynamic",
				"url":"http://192.168.90.112:6070/oms/arcgisrest/业务图层/BPDK_320000/MapServer",
				"visible":true,
				"xMaxExtent":121.93218377900007,
				"xMinExtent":116.35703719600008,
				"xzdm":"320000",
				"yMaxExtent":35.12448058100006,
				"yMinExtent":30.762607439000078,
				"year":2016
			}
		]
	},
	"name":"test",
	"title":"江苏省国土资源 一张图",
	"widgetContainer":{
		"widgets":[
			{
				"collapsible":false,
				"config":{
					"hideInvisibleLayer":true
				},
				"display":false,
				"icon":"fa-bars",
				"id":"LayerList",
				"label":"图层控制",
				"open":false,
				"url":"LayerList",
				"weight":0
			},
			{
				"collapsible":false,
				"config":{
					"layers":[],
					"merge":false
				},
				"display":true,
				"icon":"fa-search",
				"id":"82CFB17C-7687-F900-0555-FC470B2BF307",
				"label":"信息查询",
				"open":false,
				"url":"Query",
				"weight":4
			},
			{
				"collapsible":false,
				"config":{
					"layers":[
						{
							"enableVideo":false,
							"html":"",
							"layerIndex":"0",
							"layerName":"GDDK_320000",
							"link":{
								"defaultOpen":false,
								"tip":"",
								"url":""
							},
							"returnFields":[
								{
									"alias":"DKBH",
									"name":"DKBH",
									"type":"STRING"
								},
								{
									"alias":"DKMC",
									"name":"DKMC",
									"type":"STRING"
								},
								{
									"alias":"DKMJ",
									"name":"DKMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"XZQ_DM",
									"name":"XZQ_DM",
									"type":"STRING"
								},
								{
									"alias":"BH",
									"name":"BH",
									"type":"STRING"
								}
							],
							"serviceId":"016a061eb88f4028daf06a05eccb0039",
							"titleField":{
								"alias":"DKBH",
								"name":"DKBH"
							},
							"type":"field"
						},
						{
							"enableVideo":false,
							"html":"",
							"layerIndex":"0",
							"layerName":"BPDK_320000",
							"link":{
								"defaultOpen":false,
								"tip":"",
								"url":""
							},
							"returnFields":[
								{
									"alias":"地块名称",
									"name":"DKNAME",
									"type":"STRING"
								},
								{
									"alias":"项目名称",
									"name":"PRONAME",
									"type":"STRING"
								},
								{
									"alias":"地块用途",
									"name":"USAGE",
									"type":"STRING"
								},
								{
									"alias":"申请单位名称",
									"name":"UNIT_NAME",
									"type":"STRING"
								},
								{
									"alias":"项目类型",
									"name":"APP_TYPE",
									"type":"STRING"
								},
								{
									"alias":"地块面积",
									"name":"DIKUAI_AREA",
									"type":"DOUBLE"
								}
							],
							"serviceId":"016a05eebf1b4028daf06a05eccb0017",
							"titleField":{
								"alias":"地块名称",
								"name":"DKNAME"
							},
							"type":"field"
						}
					]
				},
				"display":false,
				"icon":"fa-info",
				"id":"17101A7E-844D-6288-444F-23468D9D51E1",
				"label":"属性识别",
				"open":false,
				"url":"Identify",
				"weight":6
			},
			{
                "collapsible":false,
                "config":{
                    "layerNames":[
                        {
                            "desc":"地类图斑",
                            "layerName":"DLTB"
                        },
                        {
                            "desc":"现状地物",
                            "layerName":"XZDW_H_2016"
                        },
                        {
                            "desc":"供地地块",
                            "layerName":"GDDK"
                        }
                    ],
                    "pushDsName":"test",
                    "queryDsName":"test2",
                    "role":"shi"
                },
                "display":false,
                "icon":"fa-exchange",
                "id":"17101A7E-844D-6288-444F-23468D9D51E2",
                "label":"数据共享",
                "open":false,
                "url":"TP/mas/DataShare",
                "weight":7
            }
		],
		"widgetsGroup":[
			{
				"icon":"fa-bar-chart",
				"id":"Analysis",
				"label":"统计分析",
				"type":5,
				"url":"Analysis",
				"weight":0,
				"widgets":[]
			},
			{
				"icon":"fa-wrench",
				"id":"Tool",
				"label":"常用工具",
				"type":6,
				"url":"Tool",
				"weight":0,
				"widgets":[
					{
						"collapsible":false,
						"config":{
							"areaunits":[
								{
									"abbr":"平方米",
									"conversion":"1",
									"precision":"3"
								},
								{
									"abbr":"平方千米",
									"conversion":"0.000001",
									"precision":"3"
								},
								{
									"abbr":"亩",
									"conversion":"0.0015",
									"precision":"3"
								},
								{
									"abbr":"公顷",
									"conversion":"0.0001",
									"precision":"3"
								}
							],
							"defaultWkid":"2364",
							"distanceunits":[
								{
									"abbr":"米",
									"conversion":"1",
									"precision":"3"
								},
								{
									"abbr":"千米",
									"conversion":"0.001",
									"precision":"3"
								}
							],
							"showAdvance":false,
							"spatialrefs":[
								{
									"name":"Xian_1980_3_Degree_GK_Zone_40",
									"wkid":"2364"
								},
								{
									"name":"Xian_1980_3_Degree_GK_CM_120E",
									"wkid":"2385"
								}
							],
							"textsymbol":{
								"color":"0xe76049",
								"font":"微软雅黑",
								"size":"15"
							}
						},
						"display":false,
						"group":"Tool",
						"icon":"",
						"id":"MapMeasure",
						"label":"地图量算",
						"open":false,
						"url":"Measure",
						"weight":3
					},
					{
						"collapsible":false,
						"config":{
							"author":"作者",
							"copyright":"版权",
							"customTextItems":[],
							"title":"打印标题",
							"url":"http://192.168.1.125:6080/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task"
						},
						"display":false,
						"group":"Tool",
						"icon":"/omp/img/menu/print.png",
						"id":"Print",
						"label":"打印",
						"open":false,
						"url":"Print",
						"weight":0
					},
					{
						"collapsible":false,
						"display":false,
						"group":"Tool",
						"icon":"/omp/img/menu/mark.png",
						"id":"Mark",
						"label":"标记",
						"open":false,
						"url":"Mark",
						"weight":0
					},
					{
						"collapsible":false,
						"config":{
							"importStyle":{
								"fill_color":"0x00CC99",
								"outline_color":"0xea3a36"
							},
							"importTitle":"导入地块名称",
							"selectStyle":{
								"fill_color":"0xff0000",
								"outline_color":"0xFF0033"
							}
						},
						"display":false,
						"group":"Tool",
						"icon":"/omp/img/menu/assessment.png",
						"id":"IOWidget",
						"label":"导入导出",
						"open":false,
						"url":"IOWidget",
						"weight":0
					}
				]
			}
		]
	},
	"widgets":[
		{
			"collapsible":false,
			"config":{
				"style":"normal"
			},
			"display":true,
			"id":"MenuBar",
			"open":false,
			"url":"MenuBar",
			"weight":0
		},
		{
			"collapsible":false,
			"display":true,
			"id":"Navigation",
			"open":false,
			"url":"Navigation",
			"weight":0
		},
		{
			"collapsible":false,
			"config":{
				"style":"default"
			},
			"display":true,
			"open":true,
			"url":"Scalebar",
			"weight":0
		},
		{
			"collapsible":false,
			"display":true,
			"id":"Region",
			"open":false,
			"url":"Region",
			"weight":0
		},
		{
			"collapsible":false,
			"config":{
				"layers":[]
			},
			"display":false,
			"icon":"fa-location",
			"id":"Location",
			"label":"定位",
			"open":false,
			"url":"Location",
			"weight":0
		}
	]
}