{
	"coordinateVisible":true,
	"createAt":"2014-10-09 14:06:43",
	"defaultRegionCode":"320000",
	"description":"",
	"dockWidgets":[{
		"collapsible":false,
		"config":{
			"expandLevel":1
		},
		"display":true,
		"icon":"glyphicon glyphicon-tasks",
		"id":"DataList",
		"label":"数据",
		"open":false,
		"url":"DataList",
		"weight":0
	}],
	"geometryService":{
		"url":"http://172.18.2.91:6080/arcgis/rest/services/Utilities/Geometry/GeometryServer"
	},
	"logo":"/omp/static/img/new/logo.jpg",
	"map":{
		"baseLayers":[],
		"defaultScale":0,
		"initExtent":{
			"xmax":123.71583187489176,
			"xmin":114.72643218210828,
			"ymax":35.36092789180001,
			"ymin":32.174607498601794
		},
		"operationalLayers":[
			{
				"alias":"江苏政区2015",
				"alpha":1,
				"category":"基础地理",
				"group":"013fc688b35f2c92825b3fc23fe80057",
				"id":"0158336bce132c9282de583367510002",
				"index":1,
				"name":"JSZQ_2015",
				"type":"tiled",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/基础地理/JSZQ_2015/MapServer",
				"visible":true,
				"xzdm":"320000",
				"year":2015
			},
			{
				"alias":"遥感监测2015",
				"alpha":1,
				"category":"遥感影像",
				"group":"013fc688f1d52c92825b3fc23fe80059",
				"id":"0158163b2f162c9282de5816009f001a",
				"index":2,
				"name":"YGJC_2015working",
				"type":"tiled",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/遥感影像/YGJC_2015working/MapServer",
				"visible":false,
				"xzdm":"320000",
				"year":2015
			},
			{
				"alias":"报批地块",
				"alpha":1,
				"category":"土地管理",
				"group":"014051b0e3692c92825b404c8a430314",
				"id":"0143b79734332c9282de43b3f715002f",
				"index":3,
				"name":"BPDK_2013",
				"type":"dynamic",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/%E5%9C%9F%E5%9C%B0%E7%AE%A1%E7%90%86/BPDK_2013/MapServer",
				"visible":true,
				"xzdm":"320000",
				"year":2013
			},
			{
				"alias":"行政界线2015",
				"alpha":1,
				"category":"基础地理",
				"group":"013fc688b35f2c92825b3fc23fe80057",
				"id":"0157f4769d322c9282de57cdba8b01db",
				"index":4,
				"name":"XZJX_2015",
				"type":"tiled",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/基础地理/XZJX_2015/MapServer",
				"visible":true,
				"xzdm":"320000",
				"year":2015
			},
			{
				"alias":"土地利用现状2015",
				"alpha":1,
				"category":"土地利用现状",
				"group":"0151667b199f2c9282de51660c670003",
				"id":"0157fc1a9ffc2c9282de57fbc9fa0092",
				"index":5,
				"name":"TDLY_2015",
				"type":"tiled",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/%E5%9C%9F%E5%9C%B0%E5%88%A9%E7%94%A8%E7%8E%B0%E7%8A%B6/TDLY_2015/MapServer",
				"visible":false,
				"xzdm":"320000",
				"year":2015
			},
			{
				"alias":"土地利用现状2014",
				"alpha":1,
				"category":"土地利用现状",
				"group":"0151667b199f2c9282de51660c670003",
				"id":"014fcfee74202c9282de4f4ad36b01bd",
				"index":6,
				"name":"TDLY_2014",
				"type":"tiled",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/%E5%9C%9F%E5%9C%B0%E5%88%A9%E7%94%A8%E7%8E%B0%E7%8A%B6/TDLY_2014/MapServer",
				"visible":false,
				"xzdm":"320000",
				"year":2014
			},
			{
				"alias":"供地地块",
				"alpha":1,
				"category":"土地管理",
				"group":"014051b0e3692c92825b404c8a430314",
				"id":"0143d2b5b43e2c9282de43d29bdf002c",
				"index":7,
				"name":"GDDK_2013",
				"type":"dynamic",
				"url":"http://172.18.2.94:8080/oms/arcgisrest/土地管理/GDDK_2013/MapServer",
				"visible":true,
				"xMaxExtent":121.90833920300001,
				"xMinExtent":116.444840848,
				"xzdm":"320000",
				"yMaxExtent":35.120583656,
				"yMinExtent":30.77389556,
				"year":2013
			}
		]
	},
	"heatMapConfig":{
	    "queryUrl":"http://172.18.2.94:8080/oms/arcgisrest/%E5%9F%BA%E7%A1%80%E5%9C%B0%E7%90%86/JSZQ_2015/MapServer/12",
	    "queryAttr":["ObjectID","XZQMC","XZQDM"]
	},
	"name":"ga",
	"title":"江苏省国土资源“互联网+”服务与监管大数据平台",
	"widgetContainer":{
		"widgets":[
			{
				"collapsible":false,
				"config":{},
				"display":true,
				"icon":"fa-list",
				"id":"GeoAnalytic",
				"label":"GA",
				"open":false,
				"url":"TP/st/GeoAnalytic",
				"weight":2
			},
			{
				"collapsible":false,
				"config":{},
				"display":true,
				"icon":"fa-list",
				"id":"LayerList",
				"label":"图层控制",
				"open":false,
				"url":"LayerList",
				"weight":2
			},
			{
                "collapsible":false,
                "config":{
                    "queryUrl":"http://172.18.2.94:8080/oms/arcgisrest/%E5%9F%BA%E7%A1%80%E5%9C%B0%E7%90%86/JSZQ_2015/MapServer/12",
                    "fields":[
                        {
                        "name": "OBJECTID",
                        "alias": "OBJECTID",
                        "type": "esriFieldTypeOID"
                                 },
                        {
                        "name": "XZQDM",
                        "alias": "行政区代码",
                        "type": "esriFieldTypeString"
                                 },
                        {
                        "name": "XZQMC",
                        "alias": "行政区名称",
                        "type": "esriFieldTypeString"
                             }
                         ],
                    "where":" 1=1 ",
                    "blurRadius":55,
                    "maxPixelIntensity":200,
                    "minPixelIntensity":30
                },
                "display":true,
                "icon":"fa-list",
                "id":"HeatMap",
                "label":"热力图",
                "open":false,
                "url":"HeatMap",
                "weight":2
			},
			{
				"collapsible":false,
				"config":{
					"exportType":"txt,xls,cad,shp,bj",
					"importStyle":{
						"fill_color":"#000099",
						"outline_color":"#cc0033"
					},
					"importTitle":"导入地块名称",
					"importType":"bj,shp,txt,xls,cad",
					"layers":[{
						"layerIndex":1,
						"layerName":"SDE.BPDK_320000",
						"returnFields":[
							{
								"alias":"地块名称",
								"name":"DKNAME",
								"type":"STRING"
							},
							{
								"alias":"项目名称",
								"name":"PRONAME",
								"type":"STRING"
							},
							{
								"alias":"地块用途",
								"name":"USAGE_",
								"type":"STRING"
							},
							{
								"alias":"申请单位名称",
								"name":"UNIT_NAME",
								"type":"STRING"
							},
							{
								"alias":"行政代码",
								"name":"REGIONCODE",
								"type":"STRING"
							},
							{
								"alias":"报件名称",
								"name":"PCMC",
								"type":"STRING"
							}
						],
						"serviceId":"0143b79734332c9282de43b3f715002f",
						"titleField":{
							"alias":"地块名称",
							"name":"DKNAME"
						},
						"type":"field"
					}],
					"selectStyle":{
						"fill_color":"#0000cc",
						"outline_color":"#00ff00"
					}
				},
				"display":false,
				"group":"1A8EF898-E4B9-F0BC-6C65-13F551E849C8",
				"icon":"/omp/img/menu/assessment.png",
				"id":"6A0C7B00-AE5D-5315-DB36-EB5E3C860901",
				"label":"导入导出",
				"open":false,
				"url":"IOWidget",
				"weight":2
			},
			{
				"collapsible":false,
				"config":{
					"areaunits":[
						{
							"abbr":"平方米",
							"conversion":"1",
							"precision":"3"
						},
						{
							"abbr":"平方千米",
							"conversion":"0.000001",
							"precision":"3"
						},
						{
							"abbr":"亩",
							"conversion":"0.0015",
							"precision":"3"
						},
						{
							"abbr":"公顷",
							"conversion":"0.0001",
							"precision":"3"
						}
					],
					"defaultWkid":"2364",
					"distanceunits":[
						{
							"abbr":"米",
							"conversion":"1",
							"precision":"3"
						},
						{
							"abbr":"千米",
							"conversion":"0.001",
							"precision":"3"
						}
					],
					"openMapPopup":false,
					"showAdvance":false,
					"spatialrefs":[
						{
							"name":"Xian_1980_3_Degree_GK_Zone_40",
							"wkid":"2364"
						},
						{
							"name":"Xian_1980_3_Degree_GK_CM_120E",
							"wkid":"2385"
						}
					],
					"textsymbol":{
						"color":"0xe76049",
						"font":"微软雅黑",
						"size":"15"
					}
				},
				"display":true,
				"icon":"fa-asterisk",
				"id":"85F52884-CB7D-C484-2256-F39FB593F293",
				"label":"地图量算",
				"open":false,
				"url":"Measure",
				"weight":3
			},
			{
				"collapsible":false,
				"config":{
					"filterAfterQuery":false,
					"layers":[
						{
							"html":"",
							"layerIndex":0,
							"layerName":"SDE.GDDK_340521",
							"layerUrl":"http://192.168.50.169:8088/oms/arcgisrest/当涂分析/GDDK_340521/MapServer/0",
							"link":{
								"url":"http://www.baidu.com?q=${YDDW}"
							},
							"queryFields":{
								"fields":[{
									"alias":"XMMC",
									"name":"XMMC",
									"operator":"like",
									"type":"string"
								}],
								"prefix":"%"
							},
							"returnFields":[
								{
									"alias":"GDZT",
									"name":"GDZT",
									"type":"STRING"
								},
								{
									"alias":"XMMC",
									"name":"XMMC",
									"operator":"like",
									"type":"string"
								},
								{
									"alias":"YDDW",
									"name":"YDDW",
									"type":"STRING"
								}
							],
							"serviceId":"0146fafab5ab402881fd46d7406500ae",
							"titleField":{
								"alias":"XMMC",
								"name":"XMMC"
							},
							"type":"field"
						},
						{
							"html":"",
							"layerIndex":0,
							"layerName":"SDE.JCTB_2012",
							"layerUrl":"http://192.168.50.169:8088/oms/arcgisrest/当涂分析/JCTB_2012/MapServer/0",
							"link":{
								"url":"javascript:test();"
							},
							"queryFields":{
								"fields":[
									{
										"alias":"所在乡镇名称",
										"name":"XZMC",
										"operator":"like",
										"type":"string"
									},
									{
										"alias":"乡镇代码",
										"name":"XZDM",
										"operator":"like",
										"type":"string"
									},
									{
										"alias":"图斑编号",
										"name":"JCBH",
										"operator":"like",
										"type":"string"
									}
								],
								"prefix":"%"
							},
							"returnFields":[
								{
									"alias":"图斑编号",
									"name":"JCBH",
									"operator":"like",
									"type":"string"
								},
								{
									"alias":"标识码",
									"name":"BSM",
									"type":"STRING"
								},
								{
									"alias":"所在乡镇名称",
									"name":"XZMC",
									"operator":"like",
									"type":"string"
								},
								{
									"alias":"乡镇代码",
									"name":"XZDM",
									"operator":"like",
									"type":"string"
								},
								{
									"alias":"项目名称",
									"name":"XMMC",
									"type":"STRING"
								},
								{
									"alias":"建设单位",
									"name":"JSDW",
									"type":"STRING"
								},
								{
									"alias":"监测面积",
									"fixed":3,
									"name":"JCMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"图斑类型",
									"name":"TBLX",
									"type":"STRING"
								},
								{
									"alias":"耕地面积",
									"fixed":3,
									"name":"GDMJ01",
									"type":"DOUBLE"
								},
								{
									"alias":"已报批面积",
									"fixed":3,
									"name":"BPMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"已报批耕地面积",
									"fixed":3,
									"name":"BPGDMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"未报批面积",
									"fixed":3,
									"name":"WBPMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"未报批耕地面积",
									"fixed":3,
									"name":"WBPGDMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"已供地面积",
									"fixed":3,
									"name":"GDMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"未供地面积",
									"fixed":3,
									"name":"WGDMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"允许建设区面积",
									"fixed":3,
									"name":"JSQMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"基本农田面积",
									"fixed":3,
									"name":"JBNTMJ",
									"type":"DOUBLE"
								}
							],
							"serviceId":"0146fbe8572c402881fd46d74065014c",
							"titleField":{
								"alias":"所在乡镇名称",
								"name":"XZMC"
							},
							"type":"field"
						}
					],
					"locateOpacity":0.5,
					"merge":false,
					"popUpStyle":"infowindow"
				},
				"display":true,
				"icon":"fa-search",
				"id":"82CFB17C-7687-F900-0555-FC470B2BF307",
				"label":"信息查询",
				"open":false,
				"url":"Query",
				"weight":4
			},
			{
				"collapsible":false,
				"config":{
					"layers":[{
						"enableVideo":false,
						"html":"",
						"layerIndex":1,
						"layerName":"SDE.BPDK_320000",
						"link":{
							"tip":"超链接",
							"url":"http://www.baidu.com?q=${DKNAME}"
						},
						"returnFields":[
							{
								"alias":"地块名称",
								"name":"DKNAME",
								"type":"STRING"
							},
							{
								"alias":"项目名称",
								"name":"PRONAME",
								"type":"STRING"
							},
							{
								"alias":"地块用途",
								"name":"USAGE_",
								"type":"STRING"
							},
							{
								"alias":"申请单位名称",
								"name":"UNIT_NAME",
								"type":"STRING"
							},
							{
								"alias":"行政代码",
								"name":"REGIONCODE",
								"type":"STRING"
							},
							{
								"alias":"报件名称",
								"name":"PCMC",
								"type":"STRING"
							},
							{
								"alias":"项目类型",
								"name":"APP_TYPE",
								"type":"STRING"
							}
						],
						"serviceId":"0153694f72504028daac5368cd440003",
						"titleField":{
							"alias":"地块名称",
							"name":"DKNAME"
						},
						"type":"field"
					}],
					"leasPostUrl":"",
					"popUpStyle":"infowindow"
				},
				"display":false,
				"icon":"/omp/img/menu/identify.png",
				"id":"17101A7E-844D-6288-444F-23468D9D51E1",
				"label":"属性识别",
				"open":false,
				"url":"Identify",
				"weight":6
			}
		],
		"widgetsGroup":[
			{
				"id":"1A8EF898-E4B9-F0BC-6C65-13F551E849C8",
				"type":0,
				"weight":0,
				"widgets":[{
					"collapsible":false,
					"config":{
						"exportType":"txt,xls,cad,shp,bj",
						"importStyle":{
							"fill_color":"#000099",
							"outline_color":"#cc0033"
						},
						"importTitle":"导入地块名称",
						"importType":"bj,shp,txt,xls,cad",
						"layers":[{
							"layerIndex":"0",
							"layerName":"供地地块320000",
							"returnFields":[
								{
									"alias":"地块名称",
									"name":"DKMC",
									"type":"STRING"
								},
								{
									"alias":"地块面积",
									"name":"DKMJ",
									"type":"DOUBLE"
								},
								{
									"alias":"地块用途",
									"name":"DKYT",
									"type":"STRING"
								}
							],
							"serviceId":"0143d2b5b43e2c9282de43d29bdf002c",
							"titleField":{
								"alias":"地块名称",
								"name":"DKMC"
							},
							"type":"field"
						}],
						"selectStyle":{
							"fill_color":"#0000cc",
							"outline_color":"#00ff00"
						}
					},
					"display":false,
					"group":"1A8EF898-E4B9-F0BC-6C65-13F551E849C8",
					"icon":"/omp/img/menu/assessment.png",
					"id":"6A0C7B00-AE5D-5315-DB36-EB5E3C860901",
					"label":"导入导出",
					"open":false,
					"url":"IOWidget",
					"weight":2
				}]
			},
			{
				"icon":"",
				"id":"3EE2C807-CEE1-E0FB-AFB5-6425CF15CCB6",
				"label":"分析组",
				"type":0,
				"url":"",
				"weight":7,
				"widgets":[
					{
						"collapsible":false,
						"config":{
							"areaLimit":false,
							"dataSource":"glsj",
							"importBj":false,
							"importCad":false,
							"importTxt":true,
							"importXls":true,
							"jsonParams":[
								{
									"alias":"报批分析",
									"dataSource":"glsj",
									"funid":"bp",
									"layerName":"BPDK_320000",
									"returnFields":"DKNAME,PRONAME,USAGE",
									"visible":true
								},
								{
									"alias":"供地分析",
									"dataSource":"glsj",
									"funid":"gd",
									"layerName":"GDDK_320000",
									"returnFields":"DKBH,DKMC,DKYT",
									"visible":true
								},
								{
									"alias":"现状分析",
									"dataSource":"tdly",
									"dltb":"DLTB_H_2015",
									"funid":"xz",
									"groupBy":"QSDWMC",
									"xzdw":"XZDW_H_2015",
									"year":"2015"
								}
							],
							"level":"xinyi",
							"query":{
								"layers":[]
							},
							"showSelMode":true,
							"tdlyxzYear":[
								2011,
								2012,
								2013,
								2014
							]
						},
						"display":false,
						"group":"3EE2C807-CEE1-E0FB-AFB5-6425CF15CCB6",
						"icon":"/omp/img/menu/analysis.png",
						"id":"F53B0AF2-B2C9-C8D7-748D-DCD3C9A99958",
						"label":"综合分析",
						"open":false,
						"url":"MultipleAnalysis",
						"weight":6
					},
					{
						"collapsible":false,
						"config":{
							"areaUnit":"SQUARE",
							"dataSource":"tdly",
							"exportAnalysis":true,
							"exportType":"cad,shp",
							"importType":"bj,cad,shp,txt,xls",
							"scopeLayers":[{
								"layerName":"SDE.JCTB_2012",
								"layerUrl":"http://192.168.50.169:8088/oms/arcgisrest/当涂分析/JCTB_2012/MapServer/0",
								"returnFields":[
									{
										"alias":"项目名称",
										"name":"XMMC",
										"type":"string"
									},
									{
										"alias":"所在乡镇名称",
										"name":"XZMC",
										"type":"string"
									},
									{
										"alias":"乡镇代码",
										"name":"XZDM",
										"type":"string"
									}
								]
							}],
							"showSelMode":false,
							"year":[
								{
									"dltb":"dltb_h_2009",
									"xzdw":"xzdw_h_2009",
									"year":"2009"
								},
								{
									"dltb":"dltb_h_2015",
									"xzdw":"xzdw_h_2015",
									"year":"2015"
								}
							]
						},
						"display":false,
						"group":"3EE2C807-CEE1-E0FB-AFB5-6425CF15CCB6",
						"icon":"/omp/img/menu/analysis.png",
						"id":"2CEEAF61-839F-2CD5-A2F9-64264C491431",
						"label":"土地利用现状分析",
						"open":false,
						"url":"XzAnalysis",
						"weight":0
					},
					{
						"collapsible":false,
						"config":{
							"areaUnit":"SQUARE",
							"dataSource":"sde",
							"exportAnalysis":true,
							"exportType":"cad,shp",
							"importType":"bj,cad,shp,txt,xls",
							"scopeLayers":[{
								"layerName":"SDE.JCTB_2012",
								"layerUrl":"http://192.168.50.169:8088/oms/arcgisrest/当涂分析/JCTB_2012/MapServer/0",
								"returnFields":[
									{
										"alias":"项目名称",
										"name":"XMMC",
										"type":"string"
									},
									{
										"alias":"所在乡镇名称",
										"name":"XZMC",
										"type":"string"
									},
									{
										"alias":"乡镇代码",
										"name":"XZDM",
										"type":"string"
									}
								]
							}],
							"showSelMode":true,
							"year":"2014"
						},
						"display":false,
						"group":"3EE2C807-CEE1-E0FB-AFB5-6425CF15CCB6",
						"icon":"/omp/img/menu/analysis.png",
						"id":"FDE793E3-C133-22B0-B9E8-EDA18E3E72D4",
						"label":"规划审查分析",
						"open":false,
						"url":"GhAnalysis",
						"weight":1
					}
				]
			}
		]
	},
	"widgets":[
		{
			"collapsible":false,
			"config":{
				"style":"normal"
			},
			"display":true,
			"open":false,
			"url":"MenuBar",
			"weight":0
		},
		{
			"collapsible":false,
			"display":true,
			"open":true,
			"position":{
				"bottom":60,
				"left":0,
				"right":0,
				"top":0
			},
			"url":"Navigation",
			"weight":0
		},
		{
			"collapsible":false,
			"config":{
				"style":"default"
			},
			"display":true,
			"open":true,
			"url":"Scalebar",
			"weight":0
		},
		{
			"collapsible":false,
			"display":true,
			"open":false,
			"url":"Region",
			"weight":0
		},
		{
			"collapsible":false,
			"config":{
				"lods":[
					{
						"resolution":0.04283029810494505,
						"scale":3000000
					},
					{
						"resolution":0.01099866274749598,
						"scale":1155583.42
					},
					{
						"resolution":0.004124498458927162,
						"scale":288895.85
					}
				],
				"maxExtent":{
					"xmax":124.20372337470876,
					"xmin":114.23854068229154,
					"ymax":35.58510134945418,
					"ymin":31.33062507102963
				}
			},
			"display":false,
			"open":false,
			"position":{
				"bottom":5,
				"left":0,
				"right":0,
				"top":0
			},
			"url":"Overview",
			"weight":0
		},
		{
			"collapsible":false,
			"config":{
				"layers":[{
					"layerAlias":"SDE.BPDK_320000",
					"layerIndex":0,
					"returnFields":[
						{
							"alias":"地块ID",
							"name":"PL_PL_ID",
							"type":"STRING"
						},
						{
							"alias":"地块名称",
							"name":"DKNAME",
							"type":"STRING"
						},
						{
							"alias":"项目名称",
							"name":"PRONAME",
							"type":"STRING"
						}
					],
					"scale":"5000",
					"serviceId":"0153694f72504028daac5368cd440003"
				}],
				"locateOpacity":0.5
			},
			"display":true,
			"id":"Location",
			"label":"地图定位",
			"open":true,
			"url":"Location",
			"weight":0
		}
	]
}