package cn.gtmap.onemap.server.thirdparty.kanq.org;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2013-12-27T11:07:05.244+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "org", 
                  wsdlLocation = "http://172.18.2.70:7879/org_ser/services/org?wsdl",
                  targetNamespace = "http://service.ser.kanq.com") 
public class Org extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ser.kanq.com", "org");
    public final static QName OrgHttpSoap11Endpoint = new QName("http://service.ser.kanq.com", "orgHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://172.18.2.70:7879/org_ser/services/org?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Org.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.18.2.70:7879/org_ser/services/org?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Org(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Org(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Org() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OrgPortType
     */
    @WebEndpoint(name = "orgHttpSoap11Endpoint")
    public OrgPortType getOrgHttpSoap11Endpoint() {
        return super.getPort(OrgHttpSoap11Endpoint, OrgPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrgPortType
     */
    @WebEndpoint(name = "orgHttpSoap11Endpoint")
    public OrgPortType getOrgHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OrgHttpSoap11Endpoint, OrgPortType.class, features);
    }

}
